### ISSUE TITLE
Downloads show "Open in Finder" on Windows

### ISSUE THREAD

**Issue by matt1** [beakerbrowser/beaker#1104]
Operation System: Windows 10
Beaker version: Version: 0.8.0-prerelease.7 Electron: 2.0.5 - Chromium: 61.0.3163.100 - Node: 8.9.3

Completed downloads show a "Show in Finder" option.
Expected to say "Show in Explorer" on Windows.

I guess from looking at the code, it will say "Show in Finder" on linux too.

**Comment by matt1** [comment]
It appears that the process.platform variable is undefined when in the context of rendering the template, so this would always fall through to "Show in Finder" here https://github.com/beakerbrowser/beaker/blob/master/app/builtin-pages/com/downloads-list.js#L68

**Comment by pfrazee** [comment]
Ah. Thanks. Will fix.

**Comment by jraspiprojects** [comment]
Done.

**Comment by jraspiprojects** [comment]
And on 64-Bit Windows machines, it returns win32.

**Comment by matt1** [comment]
I believe that win32 is expected even on win64 (this is an node thing).

Might be worth leaving this bug open to make sure that Linux users also get some attention (otherwise even with this PR, they'd still get "Show in Finder" rather than something more generic like "Show in File Manager")

**Comment by jraspiprojects** [comment]
Actually we could replace that whole if statement with Show in File Manager for all!

**Comment by taravancil** [comment]
I’d like to keep the per-OS specificity

**Comment by pmario** [comment]
I'd vote for a generic button, that fits all OSes. 

Distinguishing between "Finder" and "Explorer" is not enough. For Ubuntu it's "Files" ... 

Using the OS App search for
 - "finder" shows nothing, 
 - "explorer" shows the browser. 
 - "files" shows the app, that's meant. 

Other distros may use different names for their default "File Manager" __and__ The default can be changed.

**Comment by pfrazee** [comment]
I agree with @pmario. I changed it to just say "Show in folder".

**Comment by jraspiprojects** [comment]
lol
