### ISSUE TITLE
Allow HTTP images to show on an HTTPS site

### ISSUE THREAD

**Issue by fredhampton** [beakerbrowser/beaker#94]
Operation System:OSX
Beaker Version:Latest from Master

When I go to https://itunes.apple.com/us/artist/the-jimi-hendrix-experience/id62819
The thumb nails for the albums do not show up

**Comment by pfrazee** [comment]
I was able to reproduce.

Apple's site is served over HTTPS (secure), but they're including the images over HTTP (insecure). Beaker's current behavior is not to show the HTTP assets. That may be too severe of a policy.

**Comment by fredhampton** [comment]
Is there a way to change this in our build of beaker ?

 

On September 13, 2016 at 9:06:30 AM, Paul Frazee (notifications@github.com) wrote:

I was able to reproduce.

Apple's site is served over HTTPS (secure), but they're including the images over HTTP (insecure). Beaker's current behavior is not to show the HTTP assets. That may be too severe of a policy.

**Comment by pfrazee** [comment]
I'll relax this policy. Insecure images will be allowed to display, but JS/CSS must remain secure.

**Comment by fredhampton** [comment]
Thats great !
Thanks !

 

On September 13, 2016 at 9:18:25 AM, Paul Frazee (notifications@github.com) wrote:

HTTP assets

**Comment by pfrazee** [comment]
This is going to require changes to Electron, which is upstream of me. (See https://github.com/electron/electron/issues/2749). I'll have to put this on the backburner until I have time to make a PR to them.

**Comment by fredhampton** [comment]
I have been using beaker for the last 4 days. 
It is going great.
The only issue I continue to have is that many of the sites have blank images.
Is there a way to allow this in my version of beaker ?

**Comment by pfrazee** [comment]
I'll need to make a change to software that Beaker depends on, but doesn't have control over (Electron). The turn-around time for that kind of change tends to be pretty slow. I'll try to get it done soon, but it'll take some time.

**Comment by fredhampton** [comment]
Thanks !



On September 16, 2016 at 11:43:48 AM, Paul Frazee (notifications@github.com) wrote:

I'll need to make a change to software that Beaker depends on, but doesn't have control over (Electron). The turn-around time for that kind of change tends to be pretty slow. I'll try to get it done soon, but it'll take some time.

**Comment by fredhampton** [comment]
Is this issue fixed in latest release ?

**Comment by pfrazee** [comment]
It's not. I've begun the process that will allow me to fix this, but it's
going to take some time.

**Comment by fredhampton** [comment]
ok 
thanks !!!


On September 28, 2016 at 7:47:11 AM, Paul Frazee (notifications@github.com) wrote:

It's not. I've begun the process that will allow me to fix this, but it's
going to take some time.

**Comment by pfrazee** [comment]
@fredhampton this is finally solved in master. Thank for being patient.

**Comment by fredhampton** [comment]
Thanks !!!!!


On October 18, 2016 at 12:27:30 PM, Paul Frazee (notifications@github.com) wrote:

@fredhampton this is finally solved in master. Thank for being patient.

**Comment by fredhampton** [comment]
I tried the master build and it seems that iTunes images are not showing 
Have the changes been pushed to master ?
Do I need to make any changes ?

Thanks !!


On October 18, 2016 at 12:27:30 PM, Paul Frazee (notifications@github.com) wrote:

@fredhampton this is finally solved in master. Thank for being patient.

**Comment by pfrazee** [comment]
Run `npm run burnthemall` and see if that solves it for you

**Comment by fredhampton** [comment]
After running `npm run burnthemall` I still have the issue
When I go here the thumb nails do not show 
https://itunes.apple.com/us/artist/nina-simone/id79798






On October 18, 2016 at 7:56:07 PM, Paul Frazee (notifications@github.com) wrote:

Run `npm run burnthemall` and see if that solves it for you

**Comment by pfrazee** [comment]
Oh weird, it's suddenly not working for me either. Looking into it

**Comment by pfrazee** [comment]
I'm getting inconsistent behavior, that I can't find the pattern for. I did `rm node_modules/electron` and then `npm i`, and that solved it. Not sure what's going on.

Try this:

```
npm cache clean
npm run burnthemall
```

**Comment by fredhampton** [comment]
I will give that a try 

On October 19, 2016 at 9:32:22 AM, Paul Frazee (notifications@github.com) wrote:

I'm getting inconsistent behavior, that I can't find the pattern for. I did rm node_modules/electron and then npm i, and that solved it. Not sure what's going on.

Try this:

npm cache clean
npm run burnthemall

**Comment by pfrazee** [comment]
@fredhampton don't try that yet, I don't think it'll work. Something is wrong with my deployment process. I'll keep working and get back to you

**Comment by fredhampton** [comment]
Ok
Thanks !


On October 19, 2016 at 10:28:27 AM, Paul Frazee (notifications@github.com) wrote:

@fredhampton don't try that yet, I don't think it'll work. Something is wrong with my deployment process. I'll keep working and get back to you

**Comment by pfrazee** [comment]
Ok try this again for me. Do this:

```
cd $your_electron_folder
git pull
npm cache clean
rm -Rf node_modules/electron
npm install
npm run build
npm start
```

Then open up one of these pages and LMK if you see the pics.

Thanks!

**Comment by fredhampton** [comment]
I did all of the steps still no pics…..is there a way to clear the cache from beaker ….could this be the issue ?


On October 19, 2016 at 5:11:18 PM, Paul Frazee (notifications@github.com) wrote:

Ok try this again for me. Do this:

cd $your_electron_folder
git pull
npm cache clean
rm -Rf node_modules/electron
npm install
npm run build
npm start
Then open up one of these pages and LMK if you see the pics.

Thanks!

**Comment by pfrazee** [comment]
No it has to do with a which version of electron is used. Let's see if this will be solved by my packaged release.

**Comment by pfrazee** [comment]
@fredhampton I found it. Turns out the electron binary is being cached in ~/.electron. Do the following for me:

```
cd $your_electron_folder
git pull
rm -Rf node_modules/electron
rm -Rf ~/.electron
npm install
npm run build
npm start
```

This should solve your other open issue.

**Comment by fredhampton** [comment]
it WORKED !

Thanks so much !!!


On October 21, 2016 at 12:50:02 PM, Paul Frazee (notifications@github.com) wrote:

@fredhampton I found it. Turns out the electron binary is being cached in ~/.electron. Do the following for me:

cd $your_electron_folder
git pull
rm -Rf node_modules/electron
rm -Rf ~/.electron
npm install
npm run build
npm start
This should solve your other open issue.

**Comment by pfrazee** [comment]
Great!
